version: "3"

services:
  jupyter:
    build: .
    container_name: jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - 8888:8888
    environment:
      - USER=user
      - PASSWORD=password
